timetable/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^trainstable/', include('trainstable.urls', namespace="trainstable")),
    url(r'^admin/', include(admin.site.urls)),
]

trainstable/urls.py
from django.conf.urls import url
from .views import search, station_detail, train_detail

urlpatterns = [
    url(r'^search/', search, name='search'),
    url(r'^station/(?P<station_id>[0-9]+)/$', station_detail, name='station_detail'),
    url(r'^train/(?P<train_id>[0-9]+)/$', train_detail, name='train_detail')
]

trainstable/models.py
from django.db import models
from django.db.models import Transform


class Train(models.Model):
    train_id = models.IntegerField(default=0)
    seats = models.IntegerField(default=0)

    def __unicode__(self):
        return 'Train #%s' % (
            self.id
        )


class Station(models.Model):
    station_name = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s %s" % (
            self.station_name, self.id
        )


class Route(models.Model):
    train = models.ForeignKey(Train)

    def __unicode__(self):
        return '%s' % (
            self.id
        )


class RouteStation(models.Model):
    station = models.ForeignKey(Station)
    time_arrive = models.DateTimeField(default=None, blank=True, null=True)
    time_depart = models.DateTimeField(default=None, blank=True, null=True)
    route = models.ForeignKey(Route)
    position_in_route = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s Route: %s Position in route: %s' % (
            self.route, self.station, self.position_in_route
        )

    def find_trains(self, station_from, station_to, date):
        trains_list = []
        for raw in RouteStation.objects.filter(time_depart__contains=date, station=station_from):
            trains_list.append({
                'route': raw.route,
                'station_id': raw.id,
                'time_arrive': raw.time_arrive,
                'time_depart': raw.time_depart,
                'position_in_route': raw.position_in_route
            })
        final_list = []
        for train in trains_list:
            for raw in RouteStation.objects.filter(station=station_to, route=train['route']):
                if int(raw.position_in_route) > int(train['position_in_route']):
                    final_list.append({
                        'station_from': station_from,
                        'time_depart': train['time_depart'].strftime('%H:%M, %d %b %Y'),
                        'station_to': station_to,
                        'time_arrive': raw.time_arrive.strftime('%H:%M, %d %b %Y'),
                        'train': train['route'].train
                    })
        return final_list

trainstable/forms.py
from django import forms


class TimeTableForm(forms.Form):
    station_from = forms.CharField(label='from', max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Station from'}))
    station_to = forms.CharField(label='to', max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Station to'}))
    datetime = forms.DateTimeField(
        label='when', widget=forms.TextInput(attrs={'placeholder': 'Date'}))

trainstable/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime, date, time
from .models import RouteStation, Station, Train
from .forms import TimeTableForm


def search(request):
    if request.method == 'POST':
        form = TimeTableForm(request.POST)
        if form.is_valid():
            station_from = Station.objects.get(
                station_name=str(form.data['station_from']))
            station_to = Station.objects.get(
                station_name=str(form.data['station_to']))
            datetime = form.data['datetime']
            finder = RouteStation()
            trains_list = finder.find_trains(
                station_from, station_to, datetime)
            return render(request, 'trainstable/timetable.html', {
                'trains_list': trains_list,
                'station_from': station_from,
                'station_to': station_to,
                'date': datetime,
            })
    else:
        form = TimeTableForm()
    return render(request, 'trainstable/search.html', {'form': form})


def station_detail(request, station_id):
    station = get_object_or_404(Station, pk=station_id)
    return render(request, 'trainstable/station.html', {'station': station})


def train_detail(request, train_id):
    train = get_object_or_404(Train, pk=train_id)
    return render(request, 'trainstable/train.html', {'train': train})

trainstable/templates/trainstable/input_form.html
{% for field in form %}
  <div class="form-group">
    <label class="sr-only" for="InputFrom">{{ field.label }}</label>
    {{ field }}
  </div>
{% endfor %}
<button type="submit" class="btn btn-info" title="">Search!</button>

trainstable/templates/trainstable/search.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


<p style="padding-top:20px;"></p>

<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title">Where do you want to go?</h3>
                </div>
                <div class="panel-body">
                    <form class="form-inline" action="/trainstable/search/" method="POST">
                        {% csrf_token %}
                        {% include "trainstable/input_form.html" %}
                    </form>
                </div>
            </div>
        </div>
    </div>  
</div>

trainstable/templates/trainstable/station.html
{# Load the tag library #}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<p style="padding-top:20px;"></p>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title"> {{station.station_name}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

trainstable/templates/trainstable/timetable.html
{# Load the tag library #}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<p style="padding-top:20px;"></p>
{% if trains_list %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <h3 class="panel-title"><a href="{% url 'trainstable:station_detail' station_from.id %}">{{ station_from.station_name }}</a><i class="glyphicon glyphicon-menu-right"></i><a href="{% url 'trainstable:station_detail' station_to.id %}">{{station_to.station_name}}</a><span class="pull-right">{{ date }}</span></h3>
                    </div>
                    <table class="table table-striped">
                        <thead>
                            <tr class="info">
                                <td>Train #</td>
                                <td>Departure time</td>
                                <td>Arrival time</td>
                            </tr>
                        </thead>
                        <tbody>
                        {% for route in trains_list %}
                        <tr>
                            <td><a href="{% url 'trainstable:train_detail' route.train.id %}">{{route.train.id}}</a></td>
                            <td>{{route.time_depart}}</td>
                            <td>{{route.time_arrive}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="panel-title">Have a nice trip!</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <h3 class="panel-title">No available trains. We are so sorry! ;(</h3>
                    </div>
                    <div class="panel-body">
                        <a href="trainstable/index/"><button type="submit" class="btn btn-info" title="">Try again!</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

trainstable/templates/trainstable/train.html
{# Load the tag library #}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<p style="padding-top:20px;"></p>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title">Train# {{train.train_id}}</h3>
                </div>
                <div class="panel-body">
                    <h3 class="panel-title">Seats: {{train.seats}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>